### ISSUE TITLE
Add an "offline" button to vector layers 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#135] opened 2018-08-23 10:25 UTC
Chrome can handle quite large vector data sets, but it can take some time to retrieve the data from GC2.
So every vector should have a Offline option, which will prevent a GC2 connection next time the layer is switch on. Just like if the browser has no network. It is important that the Offline option is stored in state. A workflow could look like this:

1. The user switch on a big vector data set and maybe add some filters.
2. The user checks the Offline option on the layer.
3. The user makes a Snapshot.
4. When the user later comes back, he runs the snapshot and the big data set is loaded from cache. Or if he just turn it off and on again.

There should also be refresh button, which will reload the data from GC2. And is should be easy to spot if a layer is offline. Using the filters on a offline layer, should alert the user, that it will grab new data from the server.

I guess this new feature will render the Force offline redundant?
 
![image](https://user-images.githubusercontent.com/3850918/44520002-f80ee680-a6ce-11e8-98b5-8bb7882b8573.png)

**Comment by sashuk** [comment] 2018-09-17 02:08
@mapcentia Probably the regular **Offline mode** control should be left, as it will declare the offline mode by default for all layers, vector layers, though, will have custom **Offline mode** control, which will allow cache and refresh vector data?

**Comment by mapcentia** [comment] 2018-09-17 06:27
@sashuk Yes, leave the Offline mode contol

**Comment by sashuk** [comment] 2018-09-21 17:02
Current thoughts:
- how to store data - as a cached response via SW (very natural way) or in the queue (huge data sets will occupy both cache and the client storage, but more controllable)?

The **goal** is not to make trips to server in order to fetch the data again and again. Possible solution:
- tell SW to return cached response in case "if anybody requests you the specific vector layer" via publish-subscribe mechanism, so the state snapshot actually contains data of what vector layers are set to be ignored in SW (layers are ignored only if they are cached, which needs to be checked every time).

**Comment by sashuk** [comment] 2018-09-25 16:49
The SW API that deals with vector layer caching

`getCachedSQLQueries(void)` - return the list of SQL queries that are already cached and their respective offline/online status

`setSQLQueryOffline(sql)` - sets the specific SQL query to be served from cache

`setSQLQueryOnline(sql)` - sets the specific SQL query to be served from server

**Comment by sashuk** [comment] 2018-09-27 07:45
Changes in separate branch https://github.com/sashuk/vidi/tree/offline-mode-controls-for-vector-layers

**Comment by sashuk** [comment] 2018-09-27 11:50
Issues:
- where to store the online/offline status of vector layers? - local storage
- how to distinguish the filtering options for the same layer? - for now get the tabke name from SQL and compare (also the SQL parsing could be used with https://www.npmjs.com/package/js-sql-parser, but it seems to be an overkill)
- what if application gets to know the online/offline state of the vector layer in the middle of loading layer from server? - wait till the current action completes
- what if vector layer is set to be offline, but there is no cached response? - when setting it offline, check. Also when the `layerTree` is built with some layers non-cached but set to be offline, check and revert them to operational state;
- what if more than one tabs are open with application at the same, how to ensure that all of them has the same online/offline state propagation between them? - publish/subscribe for service workers, keep the consistency across the application;
- the case when service worker is not available (non-TLS case) - hide the controls;
- the offline mode for vector layers is basically redirecting the SQL query request to corresponding response in the service worker? - yes, the service worker checks if it has valid cached response for the request and returns it if layer is set to be offline;
- how service worker distinguishes calls to `/api/sql`? - for now just storing [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) identifier;

**Comment by sashuk** [comment] 2018-09-27 13:44
Plan:
- :heavy_check_mark: detect the table name of the `api/sql` request;
- implement service worker API for getting list of cached `api/sql` requests;
- change the UI in `layerTree` according to the state of cache across all open tabs;
- implement cache refreshing;
- implement service worker API for setting the online or offline state of vector layer;
- make the service worker be able to detect varying filters for vector layers (no SQL tokenization, only equality or hashsum check);

**Comment by sashuk** [comment] 2018-09-28 08:09
@mapcentia Current state of the issue: `layerTree` control for setting the offline mode for vector layers works - in the demo below you can see that the `public.test_line` is loaded first time in regular mode (there are two requests in the **Network** tab, which means that service worker is requesting server). However, if we toggle the offline mode for layer, next time when it is loaded it is requested from cache (**Network** tab contains only one immediate request which results in previously cached response for similar request).

Implemented in https://github.com/sashuk/vidi/commit/c67bf1ca984d1b51d6801bc6ca3130957155f2c4. For now the issue is in MVP state, some issues are still left (the overall plan is listed in the comment above).

![offlinevectolayers](https://user-images.githubusercontent.com/1390758/46196032-86aefd00-c338-11e8-8470-e735cfbccf1b.gif)

**Comment by sashuk** [comment] 2018-10-24 01:45
@mapcentia Seems like the `Toggle offline mode` control is not really required and can be replaced with the regular **badge** that displays the offline state of the network and **two controls** that let user to make all vector layers online or offline (if the network is available and the choice can be actually made).

Custom offline mode controls for layers will have the same behaviour as the main offline mode toggle - they become offline and locked when application goes offline and they remember the actual user choice made before, as well as they can be recorded and recreated from state.

Please see the screenshot below:

![offlinemode](https://user-images.githubusercontent.com/1390758/47400776-4d1fb500-d771-11e8-8436-534d83bf54fc.png)

**Comment by sashuk** [comment] 2018-10-26 10:03
@mapcentia New offline mode controls were merged with the develop branch. Features of new offline mode controls:
- offline mode for tile vectors behaves like the old one. Offline mode for vector layers can be enabled only if there is cached data for vector layer (this is checked when applying state snapshots as well);
- offline mode settings are kept after page reload;
- offline mode settings can be passed to the state snapshot;

Issue is considered to be open until #167 is completed as many tests rely on old controls.

**Closed as completed** 2018-10-30 09:25 UTC
Labels: enhancement
