### ISSUE TITLE
No layer tree when dynamically adding layer

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#91] opened 2018-07-31 21:23 UTC
If you switch a layer on (in switchLayer.js) which are not in Meta on load, it will be added in run time.
Here Vidi is started with layers from "public", but a layer from "test" is in the anchor:
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/12/39.2358/-6.8057/test.polygon
The layer is added and visible, but there is no layer tree.

It should also work with vector layers, but here it fails completely (it didn't work in master either)
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/12/39.2358/-6.8057/v:test.polygon

**Comment by sashuk** [comment] 2018-08-01 16:07
Fixed in https://github.com/sashuk/vidi/commit/8944b44558737ebb7ba1a1e86c532de451d1ddfb and https://github.com/sashuk/vidi/commit/714cb87615efae0f7952ab8822b7d9125f90163b

Please try `tile` case https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/13/39.2626/-6.8396/test.polygon and `vector` case https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/13/39.2626/-6.8396/v:test.polygon

The bug was caused by race condition in recreating the `layerTree` upon meta renewal

**Closed by sashuk** 2018-08-01 16:07 UTC
Labels: bug, enhancement
