### ISSUE TITLE
Vectorfilters don't work

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#171] opened 2018-10-30 12:05 UTC
Filters don't get applied.
![image](https://user-images.githubusercontent.com/3850918/47716908-5bc00d80-dc44-11e8-938a-c9a000ef7f8c.png)

**Comment by sashuk** [comment] 2018-10-31 06:38
@mapcentia Could you please provide link to this installation?

**Comment by mapcentia** [comment] 2018-10-31 06:57
host: geofyn.mapcentia.com

https://dev.geofyn.dk/app/geofyn/?config=miljoevagtfyn.json#gc2_group._b_baggrundskort01.baggrundskort01/12/10.699/55.3338/v:test.registrering

**Comment by sashuk** [comment] 2018-10-31 07:51
@mapcentia Thanks! The regression is also observed (https://travis-ci.org/sashuk/vidi/builds/448703464), fixing it.

**Comment by sashuk** [comment] 2018-10-31 08:49
@mapcentia The configuration was recreated (https://vidi.alexshumilov.ru/app/geofyn/?config=miljoevagtfyn.json#stamenTonerLite/12/10.6897/55.3316/v:test.registrering, both `development` and `production` version) and filters seem to work, could you please try the latest code?

![filtering](https://user-images.githubusercontent.com/1390758/47776216-d9f7df00-dd2c-11e8-8f00-bb13ced99a8c.gif)

**Comment by mapcentia** [comment] 2018-10-31 14:39
@sashuk Could you merge master branch from https://github.com/mapcentia/vidi into your develop branch? So we can have a up-to-speed develop branch

**Comment by sashuk** [comment] 2018-10-31 16:52
@mapcentia I've merged and Filters stopped working, thanks!

**Comment by sashuk** [comment] 2018-10-31 17:38
@mapcentia The reason behind the not working vector layers is that the `createStore()` is not launched second time, so filters are not applied

https://github.com/sashuk/vidi/blob/18d61056e89c02b95a148c257f0757c0ec0dd867/browser/modules/layerTree/index.js#L649-L657

It seems working as it was initially designed (assuming that application of filters should request fresh set of features from server), could you please specify if the store reset is not allowed?

**Comment by mapcentia** [comment] 2018-10-31 19:12
@sashuk I see. I've removed my hack. The issue I tried to fix was this.
I've this in a module: https://github.com/mapcentia/watsonc/blob/master/browser/index.js#L251
This works fine, if I start Vidi and switch the layer on. 
Demo: https://watsonc-map.gc2.io/app/jupiter/chemicals
But if I start Vidi with the layer in the URL:
https://watsonc-map.gc2.io/app/jupiter/chemicals/#geodk.bright/8/10.0168/56.6774/v:chemicals.boreholes_time_series_with_chemicals
The default blue marekers are used. Switching the layer off/on will revert the marker to red circles.

**Comment by sashuk** [comment] 2018-11-02 00:37
@mapcentia The problem in case of URL-contained layer name was that the `layerTree`, before the initialization of the `watsonc` module, was already trying to load and display this layer without settings that are later provided by `watsonc` (more detailed application initialization process can be found at https://github.com/sashuk/vidi/wiki). The timeline was like this:

`layerTree creates store with default marker style > switchLayer enables and loads the vector layer with default settings > watsonc initializes and changes default settings for creating store in layerTree`

So, `watsonc` was correctly setting the style, but it was too late and the manual layer reload was required (that is why after second load of layer marker style was correct). Now `watsonc` upon its initalization (after passing new settings in vector layer store) just takes the list of active layers and reloads them, so the style is applied and user sees the vector layer with red circles from the very beginning.

Commit in `watconc` repo https://github.com/sashuk/watsonc/commit/e5c6b675de5f6a05e8cb25b24bd95c3e0083115c

**Closed by sashuk** 2018-11-02 00:37 UTC
Labels: bug, question
