### ISSUE TITLE
Reorder layers in sub-groups doesn't work in all sub-groups

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#234] opened 2018-12-21 07:44 UTC
On this site: https://vidi.envirogissolutions.co.za/app/envirogis/public
the only layers that can be reordered within a sub-group is `Roads` in the `Orientation`  Group. It doesn't work on `Agro-Climate`,  `Agro-Soils` and Others. Here you can only reorder the whole sub-groups.

**Comment by mapcentia** [comment] 2018-12-21 07:44
![](https://github.trello.services/images/mini-trello-icon.png) [The only layers that can be reordered / or moved within Sub group is Roads in the Orientation Main Group. It doesn't work on Agro-Climate & Agro-Soils and Others](https://trello.com/c/SZpktAPx/17-the-only-layers-that-can-be-reordered-or-moved-within-sub-group-is-roads-in-the-orientation-main-group-it-doesnt-work-on-agro-cl)

**Comment by sashuk** [comment] 2018-12-24 12:54
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/be0ae5f5a21cb66218d868af9c3b31cb78e27bcb

**Comment by lossoE** [comment] 2019-07-13 00:29
@sashuk @mapcentia 
This bug has appear again and Transparency tool does appear on some layers when loaded on vidi using a config but it is working if viewed directly using the schema vidi link on GC2.

Thx

**Comment by lossoE** [comment] 2019-07-24 08:46
@sashuk @mapcentia 

Any progresss? Received many complaints from end users.

Thx

**Comment by sashuk** [comment] 2019-07-24 12:34
@lossoE Hello! I am just getting to the issue, hope to finish it tonight.

**Comment by lossoE** [comment] 2019-07-24 13:53
@sashuk 
Great!

**Comment by sashuk** [comment] 2019-07-24 14:00
@lossoE Could you please the URL if the installation is the public one?

**Comment by lossoE** [comment] 2019-07-24 14:09
@sashuk @mapcentia 
Here we go : https://vidi.envirogissolutions.co.za/app/envirogis/?config=envirogis_c2.json#bingRoad/6/24.895/-28.6327/

But the server is taking sometime to load the data. Not sure what the issue is.

**Comment by sashuk** [comment] 2019-07-24 14:10
Thank you very much!
________________

Aleksandr Shumilov

Tel: 79501017750
Skype: sashuk-morehod
Email: alexshumilov@yahoo.com
Web-site: https://alexshumilov.ru

**Comment by lossoE** [comment] 2019-07-24 14:13
@sashuk @mapcentia Vidi not responding I will check again shortly and let you know.

**Comment by sashuk** [comment] 2019-07-24 14:51
@lossoE Could you please also specify what layers (with full group route to the layer) are not sorted correctly?

**Comment by lossoE** [comment] 2019-07-25 02:02
@sashuk apologies i had a chache issue on machine. You can't move any parent category or layers in a subgroup on vidi at the moment on all map instance on production. That function is disable at the moment. Previously it was possible to move it up or down.

**Comment by sashuk** [comment] 2019-07-25 05:20
@lossoE Could you please specify if it is not working on https://vidi.envirogissolutions.co.za/app/envirogis/?config=envirogis_c2.json#bingRoad/6/24.895/-28.6327/? I've just checked and it still has the old version of code.

**Comment by lossoE** [comment] 2019-07-25 06:03
@sashuk I have checked it is not working on the provided URL on my side.

**Comment by sashuk** [comment] 2019-07-25 06:22
@lossoE Correct, as the provided URL does not have the latest codebase. Please rebuild from the https://github.com/sashuk/vidi.git `master` branch, below is the screencast with the initial empty cache (as you can see the codebase contain now the old-code line that logs into the console).

![cache](https://user-images.githubusercontent.com/1390758/61850709-8b582980-aee7-11e9-8e16-d43f22ca99d3.gif)

**Comment by lossoE** [comment] 2019-07-25 06:31
@sashuk Apologies Alek it's a user problem. On this side. It is working. To move layers  users needs to move mouse over the three dots on the right. You close this query. Most appreciated!

**Comment by sashuk** [comment] 2019-07-25 06:32
@lossoE Great, happy to hear that! Could you please also check the https://github.com/sashuk/vidi/issues/195?

**Closed** 2019-07-25 14:16 UTC
Labels: bug, question
